# Generated by Django 2.1.7 on 2019-03-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0001_initial'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeachRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(help_text='任教课程', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
                ('teach_class', models.ForeignKey(help_text='任教班级', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.Class')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher')),
                ('term', models.ForeignKey(help_text='任教学期', null=True, on_delete=django.db.models.deletion.SET_NULL, to='terms.Term')),
            ],
        ),
    ]
