version: "3.5"

services:
  tianchi-client_build:
    build: ../
    container_name: "tianchi-client_build"
    volumes:
      - dist:/usr/src/app/dist

  tianchi-client_web:
    image: nginx
    ports:
      - 80:80
    container_name: "tianchi-client_web"
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
