# Generated by Django 2.1.7 on 2019-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('nation', models.CharField(max_length=20, verbose_name='民族')),
                ('born_year', models.IntegerField(verbose_name='出生年份')),
                ('native_place', models.CharField(max_length=255, verbose_name='民族')),
                ('residence_type', models.IntegerField(choices=[(1, '城镇')], verbose_name='家庭类型')),
                ('policy', models.IntegerField(choices=[(1, '共青团员'), (2, '少先队员'), (3, '共产党员'), (4, '一般'), (5, '民主党派')], verbose_name='政治面貌')),
                ('is_stay_school', models.BooleanField(default=False, verbose_name='是否住校')),
                ('is_left', models.BooleanField(default=False, verbose_name='是否退学')),
                ('room_num', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
