# Generated by Django 2.1.7 on 2019-03-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('terms', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_class', models.ForeignKey(help_text='所在班级', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.Class')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='term',
            field=models.ForeignKey(help_text='学生所处学期', null=True, on_delete=django.db.models.deletion.SET_NULL, to='terms.Term'),
        ),
    ]
