# Generated by Django 2.1.7 on 2019-03-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190322_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='born_year',
            field=models.IntegerField(null=True, verbose_name='出生年份'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nation',
            field=models.CharField(max_length=20, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='native_place',
            field=models.CharField(max_length=255, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='policy',
            field=models.IntegerField(choices=[(1, '共青团员'), (2, '少先队员'), (3, '共产党员'), (4, '一般'), (5, '民主党派')], null=True, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='student',
            name='residence_type',
            field=models.IntegerField(choices=[(1, '城镇')], null=True, verbose_name='家庭类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
