# Generated by Django 2.1.7 on 2019-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190323_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='native_place',
            field=models.CharField(max_length=255, null=True, verbose_name='出生地'),
        ),
    ]
