# Generated by Django 2.1.7 on 2019-03-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoqins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kaoqinevent',
            old_name='event_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='kaoqintype',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
