# Generated by Django 2.1.7 on 2019-03-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoqins', '0002_auto_20190323_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaoqinevent',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
