# Generated by Django 2.1.7 on 2019-03-23 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoqins', '0004_auto_20190323_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaoqinrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
