# Generated by Django 2.1.7 on 2019-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
