# Generated by Django 2.1.7 on 2019-03-23 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0002_auto_20190322_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
