# Generated by Django 2.1.7 on 2019-04-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190323_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='campus_name',
            field=models.IntegerField(choices=[(1, '东部校区'), (0, '白杨校区')], default=0),
        ),
    ]
