# Generated by Django 2.1.7 on 2019-05-22 01:37

from django.db import migrations, models


def get_start_year(apps, schema_editor):
    Class = apps.get_model('classes', 'Class')
    for obj in Class.objects.all():
        year = obj.studentrecord_set.select_related(
            'term'
        ).last()
        if year:
            obj.start_year = year.term.start_year
            obj.save()
            continue
        print('error_id:{}'.format(obj.id))


class Migration(migrations.Migration):
    dependencies = [
        ('classes', '0003_class_campus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.RunPython(get_start_year, reverse_code=migrations.RunPython.noop),
    ]
