# Generated by Django 2.1.7 on 2019-04-18 13:57

from django.db import migrations, models

# get each subexam's standard
from django.db.models import Max
from progress.bar import Bar


def get_record_year(apps, schema_editor):
    CourseRecord = apps.get_model('courses', 'CourseRecord')
    StudentRecord = apps.get_model('students', 'StudentRecord')
    bar = Bar('Processing', max=CourseRecord.objects.all().count())
    for course_record in CourseRecord.objects.all():
        bar.next()
        year = StudentRecord.objects.filter(
            student_id=course_record.student.id
        ).select_related('term').order_by('term__end_year').last().term.end_year
        course_record.year = year
        course_record.save()
    bar.finish()


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0003_add_course_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(get_record_year, reverse_code=migrations.RunPython.noop),
    ]
