# Generated by Django 2.1.7 on 2019-05-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_auto_20190418_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='权重')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='WordCloudTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标签名称')),
                ('description', models.CharField(default='', max_length=255, verbose_name='描述')),
            ],
        ),
        migrations.AddField(
            model_name='tagrecord',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.WordCloudTag'),
        ),
    ]
