# Generated by Django 2.1.7 on 2019-05-07 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courserecord_year'),
        ('wordcloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='权重')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.WordCloudTag')),
            ],
        ),
    ]
