# Generated by Django 2.1.7 on 2019-05-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0002_coursetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloudtag',
            name='type',
            field=models.IntegerField(choices=[(1, '学生'), (2, '课程专业')], default=1),
        ),
    ]
