# Generated by Django 2.1.7 on 2019-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(verbose_name='起始年份')),
                ('end_year', models.IntegerField(verbose_name='终止年份')),
                ('order', models.IntegerField(choices=[(1, '上半学期'), (2, '下半学期')])),
            ],
        ),
    ]
