# Generated by Django 2.1.7 on 2019-03-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrecord',
            name='dengdi',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='sub_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.SubExam'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='t_score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='z_score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
