# Generated by Django 2.1.7 on 2019-03-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190324_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecord',
            name='dengdi',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='t_score',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='z_score',
        ),
    ]
