# Generated by Django 2.1.7 on 2019-04-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190401_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
