# Generated by Django 2.1.7 on 2019-03-23 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190324_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecord',
            name='started_at',
        ),
        migrations.AddField(
            model_name='subexam',
            name='started_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
