# Generated by Django 2.1.7 on 2019-04-01 15:59

from django.db import migrations, models
from progress.bar import Bar


# from subexam's standard get each student's z_score
def get_zt_score(apps, schema_editor):
    StudentExamRecord = apps.get_model('exams', 'StudentExamRecord')
    bar = Bar('Processing', max=StudentExamRecord.objects.all().count())
    for student_exam_record in StudentExamRecord.objects.filter(score__gte=0):
        bar.next()
        sub_exam = student_exam_record.sub_exam
        if not sub_exam.standard:
            student_exam_record.z_score = 0.0
            student_exam_record.t_score = 80
            student_exam_record.save()
            continue

        score = student_exam_record.score
        average = sub_exam.total_score / sub_exam.attend_num
        student_exam_record.z_score = (score - average) / sub_exam.standard
        student_exam_record.t_score = student_exam_record.z_score * 8 + 80
        student_exam_record.save()
    bar.finish()


class Migration(migrations.Migration):
    dependencies = [
        ('exams', '0004_20190403_sub_exam_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='StudentExamRecord',
            name='z_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='StudentExamRecord',
            name='t_score',
            field=models.FloatField(default=0.0),
        ),

        migrations.RunPython(get_zt_score, reverse_code=migrations.RunPython.noop),
    ]
