# Generated by Django 2.1.7 on 2019-04-01 15:59

from django.db import migrations, models
from progress.bar import Bar


# from student's t_score get their's deng_di
def get_deng_di(apps, schema_editor):
    students = apps.get_model('exams', 'StudentExamRecord')
    bar = Bar('Processing', max=len(students.objects.all()))
    i = 1
    for student in students.objects.all().order_by(['-t_score']):
        bar.next()
        student.deng_di = i / student.sub_exam.attend_num
        i += 1
        student.save()
    bar.finish()


class Migration(migrations.Migration):
    dependencies = [
        ('exams', '0005_20190403_ZT_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='StudentExamRecord',
            name='deng_di',
            field=models.FloatField(default=0.0),
        ),

        migrations.RunPython(get_deng_di, reverse_code=migrations.RunPython.noop),
    ]
