# Generated by Django 2.1.7 on 2019-04-01 15:59

from django.db import migrations, models
from progress.bar import Bar


# from student's t_score get their's deng_di
def get_deng_di(apps, schema_editor):
    SubExam = apps.get_model('exams', 'SubExam')
    bar = Bar('Processing', max=SubExam.objects.all().count())

    for sub_exam in SubExam.objects.all():
        i = 1
        for student_exam_record in sub_exam.studentexamrecord_set.all().order_by('-t_score'):
            bar.next()
            student_exam_record.deng_di = i / sub_exam.attend_num
            i += 1
            student_exam_record.save()
    bar.finish()


class Migration(migrations.Migration):
    dependencies = [
        ('exams', '0005_20190403_ZT_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='StudentExamRecord',
            name='deng_di',
            field=models.FloatField(default=0.0),
        ),

        migrations.RunPython(get_deng_di, reverse_code=migrations.RunPython.noop),
    ]
