# Generated by Django 2.1.7 on 2019-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_20190403_dengdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='classexamrecord',
            name='highest_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classexamrecord',
            name='lowest_score',
            field=models.FloatField(default=200.0),
        ),
    ]
