# Generated by Django 2.1.7 on 2019-04-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190403_2156'),
        ('exams', '0006_20190403_dengdi'),
    ]

    operations = [
    ]
