# Generated by Django 2.1.7 on 2019-05-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_classexamrecord_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamrecord',
            name='class_rank',
            field=models.IntegerField(default=0),
        ),
    ]
